services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: mysql:9.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: running-text-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

  reverb:
    build: .
    container_name: laravel_reverb
    command: php artisan reverb:start --host=0.0.0.0
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - app
      - db
    networks:
      - app_net

  queue:
    build: .
    container_name: laravel_queue
    command: php artisan queue:work --tries=3
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  db_data:
